---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jen-k8s
  name: jen-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jen-k8s
  template:
    metadata:
      labels:
        app: jen-k8s
    spec:
      containers:
      - image: ullasasindhur/jen-k8s:<TAG>
        imagePullPolicy: Always
        name: jen-k8s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jen-k8s
  name: jen-k8s
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jen-k8s
  type: NodePort