pipeline {
  agent {
    kubernetes{
        
    }
  }
  stages {
    stage('Listing out the files') {
      steps {
        sh 'ls -alh'
      }
    }
    stage('Get information about system') {
      steps {
        sh 'cat /etc/os-release'
      }
    }
    stage('Deploying Nginx to Kubernetes') {
      steps {
        kubernetesDeploy(
          configs: 'kubernetes/deployment.yaml'
        )
    }
  }
}
}