pipeline {
  agent any
  stages {
    stage('Listing out the files') {
      steps {
        sh 'ls -alh'
      }
    }
    stage('Get information about kubernetes') {
      steps {
        sh 'kubectl get all -A'
      }
    }
  }
}