pipeline {
  agent {
    kubernetes {
        cloud 'kubernetes'
        label 'kubernetes-agent'
    }
  }
  stages {
    stage('Listing out the files') {
      steps {
        sh 'ls -alh'
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        kubernetesDeploy(
          configs: 'kubernetes/deployment.yaml',
          kubeconfigId: 'my-kubeconfig'
        )
      }
    }
  }
}